### ISSUE TITLE
Zutaten im Muffin-Rezept unvollständig

### ISSUE THREAD

**Issue by manuelprinz** [mschuetz/recipes#1]
Hallo Matthias,

im Muffin-Rezept steht in der Anweisung, dass Zucker und Butter für den Teig gemischt werden sollen. Zucker fehlt für den Teig aber in der Zutatenliste. (Außerdem ist die Zugabe des Öls nicht in der Anweisung.)

Viele Grüße,

Manuel

**Comment by mschuetz** [comment]
Danke für den Hinweis.
